// ============================================
// SmartAmbSys - Simulation / Mock Data
// ============================================

import type {
  Ambulance,
  Hospital,
  Emergency,
  DashboardStats,
} from "./types";

// ---- Ambulances ----
export const ambulances: Ambulance[] = [
  {
    id: "amb-001",
    callSign: "ALPHA-1",
    type: "ALS",
    status: "available",
    location: { lat: 28.6280, lng: 77.2190 },
    speed: 0,
    fuelLevel: 87,
    equipment: ["Defibrillator", "Ventilator", "IV Pump"],
    crew: ["Dr. Sharma", "Paramedic Ravi"],
  },
  {
    id: "amb-002",
    callSign: "BRAVO-2",
    type: "BLS",
    status: "en_route",
    location: { lat: 28.5921, lng: 77.2307 },
    speed: 48,
    fuelLevel: 62,
    equipment: ["First Aid Kit", "Oxygen Cylinder"],
    crew: ["Paramedic Soni", "Driver Prakash"],
    currentEmergencyId: "emg-001",
  },
  {
    id: "amb-003",
    callSign: "CHARLIE-3",
    type: "ALS",
    status: "at_scene",
    location: { lat: 28.6353, lng: 77.2250 },
    speed: 0,
    fuelLevel: 45,
    equipment: ["Defibrillator", "Ventilator", "Spinal Board"],
    crew: ["Dr. Mehra", "Paramedic Kiran"],
    currentEmergencyId: "emg-002",
  },
  {
    id: "amb-004",
    callSign: "DELTA-4",
    type: "BLS",
    status: "available",
    location: { lat: 28.6508, lng: 77.1855 },
    speed: 0,
    fuelLevel: 93,
    equipment: ["First Aid Kit", "Oxygen Cylinder", "Stretcher"],
    crew: ["Paramedic Amit", "Driver Ranjit"],
  },
  {
    id: "amb-005",
    callSign: "ECHO-5",
    type: "ALS",
    status: "transporting",
    location: { lat: 28.6100, lng: 77.2370 },
    speed: 35,
    fuelLevel: 31,
    equipment: ["Defibrillator", "Ventilator", "IV Pump", "ECG Monitor"],
    crew: ["Dr. Kapoor", "Paramedic Neha"],
    currentEmergencyId: "emg-003",
  },
  {
    id: "amb-006",
    callSign: "FOXTROT-6",
    type: "BLS",
    status: "dispatched",
    location: { lat: 28.6450, lng: 77.2100 },
    speed: 55,
    fuelLevel: 78,
    equipment: ["First Aid Kit", "Oxygen Cylinder"],
    crew: ["Paramedic Vikas", "Driver Suresh"],
    currentEmergencyId: "emg-004",
  },
  {
    id: "amb-007",
    callSign: "GOLF-7",
    type: "ALS",
    status: "available",
    location: { lat: 28.5800, lng: 77.2000 },
    speed: 0,
    fuelLevel: 55,
    equipment: ["Defibrillator", "Ventilator", "Drug Kit"],
    crew: ["Dr. Singh", "Paramedic Rohan"],
  },
  {
    id: "amb-008",
    callSign: "HOTEL-8",
    type: "BLS",
    status: "at_hospital",
    location: { lat: 28.6139, lng: 77.2090 },
    speed: 0,
    fuelLevel: 18,
    equipment: ["First Aid Kit", "Oxygen Cylinder"],
    crew: ["Paramedic Jaya", "Driver Hari"],
    currentEmergencyId: "emg-005",
  },
];

// ---- Hospitals ----
export const hospitals: Hospital[] = [
  {
    id: "hosp-001",
    name: "AIIMS New Delhi",
    location: { lat: 28.5672, lng: 77.2100 },
    specializations: ["Trauma", "Cardiac", "Neuro"],
    totalBeds: 2478,
    availableBeds: 312,
    icuBeds: 200,
    icuAvailable: 18,
    emergencyBeds: 120,
    emergencyAvailable: 23,
    rating: 4.8,
    contactNumber: "+91-11-26588500",
    isActive: true,
  },
  {
    id: "hosp-002",
    name: "Safdarjung Hospital",
    location: { lat: 28.5685, lng: 77.2065 },
    specializations: ["Trauma", "Burns", "General"],
    totalBeds: 1800,
    availableBeds: 245,
    icuBeds: 150,
    icuAvailable: 12,
    emergencyBeds: 100,
    emergencyAvailable: 15,
    rating: 4.2,
    contactNumber: "+91-11-26707437",
    isActive: true,
  },
  {
    id: "hosp-003",
    name: "Sir Ganga Ram Hospital",
    location: { lat: 28.6381, lng: 77.1915 },
    specializations: ["Cardiac", "Neuro", "Pediatric"],
    totalBeds: 675,
    availableBeds: 87,
    icuBeds: 80,
    icuAvailable: 6,
    emergencyBeds: 50,
    emergencyAvailable: 8,
    rating: 4.5,
    contactNumber: "+91-11-25861652",
    isActive: true,
  },
  {
    id: "hosp-004",
    name: "Lok Nayak Hospital",
    location: { lat: 28.6370, lng: 77.2395 },
    specializations: ["Trauma", "General", "Burns"],
    totalBeds: 2100,
    availableBeds: 180,
    icuBeds: 120,
    icuAvailable: 3,
    emergencyBeds: 90,
    emergencyAvailable: 5,
    rating: 3.8,
    contactNumber: "+91-11-23232400",
    isActive: true,
  },
  {
    id: "hosp-005",
    name: "Max Super Speciality, Saket",
    location: { lat: 28.5270, lng: 77.2150 },
    specializations: ["Cardiac", "Neuro", "Pediatric"],
    totalBeds: 500,
    availableBeds: 65,
    icuBeds: 60,
    icuAvailable: 9,
    emergencyBeds: 40,
    emergencyAvailable: 12,
    rating: 4.6,
    contactNumber: "+91-11-26515050",
    isActive: true,
  },
  {
    id: "hosp-006",
    name: "GTB Hospital",
    location: { lat: 28.6863, lng: 77.3105 },
    specializations: ["Trauma", "General"],
    totalBeds: 1500,
    availableBeds: 210,
    icuBeds: 90,
    icuAvailable: 7,
    emergencyBeds: 80,
    emergencyAvailable: 19,
    rating: 3.9,
    contactNumber: "+91-11-22586262",
    isActive: true,
  },
];

// ---- Emergencies ----
export const emergencyHistory: Emergency[] = [
  {
    id: "emg-001",
    callerName: "Rajesh Kumar",
    callerPhone: "+91-98765-43210",
    description: "Severe chest pain, difficulty breathing — suspected cardiac arrest",
    location: { lat: 28.5950, lng: 77.2340 },
    address: "23, Lodhi Road, New Delhi",
    severity: "P1",
    specialization: "Cardiac",
    status: "in_progress",
    assignedAmbulanceId: "amb-002",
    assignedHospitalId: "hosp-001",
    createdAt: new Date(Date.now() - 8 * 60 * 1000),
    dispatchedAt: new Date(Date.now() - 7 * 60 * 1000),
    estimatedArrivalMinutes: 4,
  },
  {
    id: "emg-002",
    callerName: "Priya Patel",
    callerPhone: "+91-98123-45678",
    description: "Multi-vehicle collision on Ring Road — 3 injured, one unconscious",
    location: { lat: 28.6350, lng: 77.2250 },
    address: "Ring Road near ISBT, New Delhi",
    severity: "P1",
    specialization: "Trauma",
    status: "in_progress",
    assignedAmbulanceId: "amb-003",
    assignedHospitalId: "hosp-004",
    createdAt: new Date(Date.now() - 15 * 60 * 1000),
    dispatchedAt: new Date(Date.now() - 14 * 60 * 1000),
    arrivedAt: new Date(Date.now() - 10 * 60 * 1000),
    estimatedArrivalMinutes: 0,
  },
  {
    id: "emg-003",
    callerName: "Amit Verma",
    callerPhone: "+91-99876-54321",
    description: "Child fell from second floor balcony — head injury, responsive",
    location: { lat: 28.6100, lng: 77.2370 },
    address: "B-45, Nizamuddin East, New Delhi",
    severity: "P2",
    specialization: "Pediatric",
    status: "in_progress",
    assignedAmbulanceId: "amb-005",
    assignedHospitalId: "hosp-003",
    createdAt: new Date(Date.now() - 22 * 60 * 1000),
    dispatchedAt: new Date(Date.now() - 21 * 60 * 1000),
    arrivedAt: new Date(Date.now() - 16 * 60 * 1000),
    estimatedArrivalMinutes: 6,
  },
  {
    id: "emg-004",
    callerName: "Sunita Devi",
    callerPhone: "+91-97654-32109",
    description: "Elderly woman collapsed at bus stop — unresponsive, weak pulse",
    location: { lat: 28.6500, lng: 77.2150 },
    address: "Near Kamla Nagar Market, New Delhi",
    severity: "P2",
    specialization: "General",
    status: "dispatched",
    assignedAmbulanceId: "amb-006",
    createdAt: new Date(Date.now() - 3 * 60 * 1000),
    dispatchedAt: new Date(Date.now() - 2 * 60 * 1000),
    estimatedArrivalMinutes: 7,
  },
  {
    id: "emg-005",
    callerName: "Mohammed Rizwan",
    callerPhone: "+91-91234-56789",
    description: "Kitchen fire burns — second degree burns on arms and face",
    location: { lat: 28.6139, lng: 77.2090 },
    address: "Chandni Chowk, Old Delhi",
    severity: "P2",
    specialization: "Burns",
    status: "completed",
    assignedAmbulanceId: "amb-008",
    assignedHospitalId: "hosp-002",
    createdAt: new Date(Date.now() - 45 * 60 * 1000),
    dispatchedAt: new Date(Date.now() - 44 * 60 * 1000),
    arrivedAt: new Date(Date.now() - 38 * 60 * 1000),
    completedAt: new Date(Date.now() - 25 * 60 * 1000),
    estimatedArrivalMinutes: 0,
  },
  {
    id: "emg-006",
    callerName: "Deepak Chandra",
    callerPhone: "+91-93456-78901",
    description: "Mild allergic reaction — facial swelling, stable vitals",
    location: { lat: 28.5800, lng: 77.2000 },
    address: "Sarojini Nagar Market, New Delhi",
    severity: "P3",
    specialization: "General",
    status: "pending",
    createdAt: new Date(Date.now() - 1 * 60 * 1000),
    estimatedArrivalMinutes: undefined,
  },
  {
    id: "emg-007",
    callerName: "Neelam Gupta",
    callerPhone: "+91-92345-67890",
    description: "Sprained ankle after fall on stairs — able to walk with support",
    location: { lat: 28.6450, lng: 77.1900 },
    address: "Karol Bagh, New Delhi",
    severity: "P4",
    specialization: "General",
    status: "pending",
    createdAt: new Date(Date.now() - 5 * 60 * 1000),
    estimatedArrivalMinutes: undefined,
  },
  {
    id: "emg-008",
    callerName: "Vikram Singh",
    callerPhone: "+91-88765-43210",
    description: "Stroke symptoms — sudden weakness on left side, slurred speech",
    location: { lat: 28.6200, lng: 77.2050 },
    address: "Connaught Place, New Delhi",
    severity: "P1",
    specialization: "Neuro",
    status: "pending",
    createdAt: new Date(Date.now() - 0.5 * 60 * 1000),
    estimatedArrivalMinutes: undefined,
  },
];

// ---- Dashboard Stats ----
export function getDashboardStats(): DashboardStats {
  const active = emergencyHistory.filter(
    (e) => e.status !== "completed"
  ).length;
  const available = ambulances.filter(
    (a) => a.status === "available"
  ).length;
  const hospitalsActive = hospitals.filter((h) => h.isActive).length;

  return {
    totalEmergencies: emergencyHistory.length,
    activeEmergencies: active,
    avgResponseTime: 8.4,
    ambulancesAvailable: available,
    ambulancesTotal: ambulances.length,
    hospitalsActive,
    co2Saved: 347,
    livesImpacted: 1243,
  };
}
